# Generated by Django 4.2.25 on 2025-10-30 14:27

from django.db import migrations, models
import django.db.models.deletion
import lms.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OHSAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(db_index=True, help_text='OHS Insider unique ID (e.g., 2019513-AIR-G-48)', max_length=50, unique=True)),
                ('bridge_subaccount_id', models.CharField(help_text='Bridge LMS subaccount identifier', max_length=100)),
                ('user_email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bridge_user_id', models.PositiveIntegerField(blank=True, null=True)),
                ('bridge_account_id', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'OHS Account',
                'verbose_name_plural': 'OHS Accounts',
                'db_table': 'ohs_account',
                'ordering': ['unique_id'],
            },
        ),
        migrations.CreateModel(
            name='OHSAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('client_id', models.CharField(default=lms.models.OHSAuth.generate_client_id, max_length=16, unique=True)),
                ('client_secret', models.CharField(default=lms.models.OHSAuth.generate_client_secret, max_length=32)),
                ('bridge_base_url', models.URLField(default='https://safetynow.bridgeapp.com', help_text='Bridge LMS base URL')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'OHS Authentication',
                'verbose_name_plural': 'OHS Authentications',
                'db_table': 'ohs_auth',
            },
        ),
        migrations.CreateModel(
            name='OHSAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_time', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='lms.ohsaccount')),
            ],
            options={
                'verbose_name': 'OHS Access Log',
                'verbose_name_plural': 'OHS Access Logs',
                'db_table': 'ohs_access_log',
                'ordering': ['-access_time'],
            },
        ),
        migrations.CreateModel(
            name='BridgeSyncTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('A', 'Account Sync'), ('U', 'User Sync'), ('AC', 'Access Grant')], max_length=2)),
                ('status', models.CharField(choices=[('P', 'Pending'), ('PR', 'Processing'), ('C', 'Completed'), ('F', 'Failed')], default='P', max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_tasks', to='lms.ohsaccount')),
            ],
            options={
                'verbose_name': 'Bridge Sync Task',
                'verbose_name_plural': 'Bridge Sync Tasks',
                'db_table': 'bridge_sync_task',
                'ordering': ['-created_at'],
            },
        ),
    ]
