# Generated by Django 4.2.25 on 2025-11-17 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0002_oauthauthorizationcode_oauthaccesstoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='ohsaccount',
            name='company_name',
            field=models.CharField(blank=True, help_text='Company name for subaccount creation', max_length=200),
        ),
        migrations.AlterField(
            model_name='ohsaccount',
            name='bridge_subaccount_id',
            field=models.CharField(help_text='Bridge LMS subaccount identifier (subdomain)', max_length=100),
        ),
    ]
