# Generated by Django 4.2.25 on 2026-01-22 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0003_ohsaccount_company_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bridge_id', models.PositiveIntegerField(db_index=True, unique=True)),
                ('title', models.CharField(db_index=True, max_length=500)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'db_table': 'course',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bridge_id', models.PositiveIntegerField(db_index=True, unique=True)),
                ('title', models.CharField(db_index=True, max_length=500)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name': 'Program',
                'verbose_name_plural': 'Programs',
                'db_table': 'program',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('prefix', models.CharField(choices=[('ohsi', 'OHSI'), ('ilt', 'ILT'), ('hri', 'HRI')], help_text='Subaccount prefix for auto-assignment (ohsi/ilt/hri)', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('courses', models.ManyToManyField(blank=True, related_name='packages', to='lms.course')),
                ('programs', models.ManyToManyField(blank=True, related_name='packages', to='lms.program')),
            ],
            options={
                'verbose_name': 'Package',
                'verbose_name_plural': 'Packages',
                'db_table': 'package',
                'ordering': ['name'],
            },
        ),
    ]
