# Generated by Django 4.2.25 on 2026-02-03 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0006_alter_course_title_alter_program_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='ohsaccount',
            name='unique_url',
            field=models.URLField(blank=True, help_text='Bridge subaccount URL (e.g., https://ohsiaircanada-safetynow.bridgeapp.com)', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='ohsaccount',
            name='bridge_subaccount_id',
            field=models.CharField(blank=True, help_text='Bridge LMS subaccount identifier (subdomain)', max_length=100),
        ),
    ]
