# Generated by Django 4.2.25 on 2026-02-03 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0007_ohsaccount_unique_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ohsaccount',
            name='prefix',
            field=models.CharField(blank=True, choices=[('ohsi', 'OHSI'), ('hri', 'HRI'), ('ilt', 'ILT')], db_index=True, help_text='Bridge subaccount prefix (ohsi/hri/ilt) - used to identify account type', max_length=10, null=True),
        ),
    ]
