# Generated by Django 4.2.25 on 2026-02-11 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0008_ohsaccount_prefix'),
    ]

    operations = [
        migrations.CreateModel(
            name='HRIAccount',
            fields=[
            ],
            options={
                'verbose_name': 'HRI Account',
                'verbose_name_plural': 'HRI Accounts',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('lms.ohsaccount',),
        ),
        migrations.CreateModel(
            name='ILTAccount',
            fields=[
            ],
            options={
                'verbose_name': 'ILT Account',
                'verbose_name_plural': 'ILT Accounts',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('lms.ohsaccount',),
        ),
        migrations.CreateModel(
            name='OHSIAccount',
            fields=[
            ],
            options={
                'verbose_name': 'OHSI Account',
                'verbose_name_plural': 'OHSI Accounts',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('lms.ohsaccount',),
        ),
        migrations.AlterModelOptions(
            name='oauthaccesstoken',
            options={'verbose_name': 'Access Token', 'verbose_name_plural': 'Access Tokens'},
        ),
        migrations.AlterModelOptions(
            name='oauthauthorizationcode',
            options={'verbose_name': 'Authorization Code', 'verbose_name_plural': 'Authorization Codes'},
        ),
        migrations.AlterModelOptions(
            name='ohsaccount',
            options={'ordering': ['unique_id'], 'verbose_name': 'Account', 'verbose_name_plural': 'Accounts'},
        ),
        migrations.AlterModelOptions(
            name='ohsauth',
            options={'verbose_name': 'Authentication', 'verbose_name_plural': 'Authentications'},
        ),
        migrations.CreateModel(
            name='PendingOIDCLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('consumed', models.BooleanField(default=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.ohsaccount')),
            ],
            options={
                'verbose_name': 'Pending OIDC Login',
                'verbose_name_plural': 'Pending OIDC Logins',
                'db_table': 'pending_oidc_login',
                'ordering': ['-created_at'],
            },
        ),
    ]
